server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/lxfly666/sprincloud2020-config
          search-paths:
            - sprincloud2020-config
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'